# Generated by Django 3.2.9 on 2022-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0002_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='movil',
            field=models.IntegerField(),
        ),
    ]
