# Generated by Django 3.2.9 on 2022-03-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0003_alter_profesor_movil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
                ('fechainicio', models.DateField()),
                ('duracion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('maxestudiante', models.IntegerField()),
                ('contacto', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrincipalApp.profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
    ]
