# Generated by Django 3.2.9 on 2022-03-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrincipalApp', '0006_auto_20220322_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='contacto',
        ),
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
