# Generated by Django 3.2.9 on 2022-03-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0008_auto_20220322_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='rol',
        ),
    ]
