# Generated by Django 4.0.3 on 2022-03-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0009_remove_persona_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='profesor',
            new_name='persona',
        ),
    ]
